kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: guestbook
  namespace: spinnaker
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: guestbook.gitops.local
      https:
      paths:
        - path: /
          backend:
            serviceName: guestbook
            servicePort: 80
