apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: declarative
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  'https://github.com/nilofe/nerd-start'
    path: many-des
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spinnaker 

